### ISSUE TITLE
rules_typescript doesn't give an error when used with a wrong version of rules_nodejs

### ISSUE THREAD

**Issue by jelbourn** [alexeagle/angular-bazel-example#12] opened 2017-11-11 01:14 UTC
```
ERROR: /usr/local/google/home/jelbourn/material2/src/cdk/keycodes/BUILD.bazel:5:1: Compiling TypeScript (devmode) //src/cdk/keycodes:keycodes failed (Exit 1)
Compilation failed TypeError: global.gc is not a function
    at Socket.<anonymous> (/usr/local/google/home/jelbourn/.cache/bazel/_bazel_jelbourn/2010aad45cf3f55bb7127948064a6254/execroot/angular_material_src/bazel-out/host/bin/external/build_bazel_rules_typescript/internal/tsc_wrapped/worker.js:122:28)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at emitReadable_ (_stream_readable.js:432:10)
    at emitReadable (_stream_readable.js:426:7)
    at readableAddChunk (_stream_readable.js:187:13)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
Target //src/lib/core:core failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.379s, Critical Path: 0.07s
FAILED: Build did NOT complete successfully
```

I encounter this error only _sometimes_ when building the `cdk/keycodes` target:
```py
package(default_visibility=["//visibility:public"])
load("@build_bazel_rules_typescript//:defs.bzl", "ts_library")

ts_library(
  name = "keycodes",
  srcs = glob(["**/*.ts"], exclude=["**/*.spec.ts"]),
  module_name = "@angular/cdk/keycodes",
  deps = [],
  tsconfig = ":tsconfig-build.json",
)
```

If I bazel clean and rebuild it goes away, but then sneaks back at some point- I'm not sure what triggers it

**Comment by jelbourn** [comment] 2017-11-11 01:16
Okay, I can make this happen pretty consistently. Seems to happen when I `bazel clean`, build one `ts_library`, then build an unrelated `ts_library`

**Comment by jelbourn** [comment] 2017-11-11 01:18
Weirdly changing to `ng_module` seems to prevent this

**Comment by alexeagle** [comment] 2017-11-12 22:54
`ts_library` uses `@build_bazel_rules_typescript//internal/tsc-wrapped` as its compiler, and this should always have the flag `--expose-gc` passed to node.
https://github.com/bazelbuild/rules_typescript/blob/master/internal/tsc_wrapped/BUILD.bazel#L53

I think this is never working, and only once you have a ts worker where the cache has filled to some threshold, do we try to call the gc.

I don't see why `ng_module` would be any better, unless maybe you don't have
`build --strategy=AngularTemplateCompile=worker` so you're not using workers for `ngc-wrapped`?

**Comment by alexeagle** [comment] 2017-11-13 01:16
I tried to repro by checking for `global.gc` at the top-level of worker.ts, but it works for me. Let's debug it tomorrow.

**Comment by jelbourn** [comment] 2017-11-13 18:04
Resolved by updating

**Comment by alexeagle** [comment] 2017-11-14 04:37
Root cause here was that rules_nodejs had a breaking change, and so you need to use a recent rules_typescript.
But rules_nodejs is published as a bazel workspace dependency (since it bootstraps the `bazel run @yarn//:yarn`) and rules_typescript is published as a npm dependency.
Still, the `ts_library` rule could probably load a constant value from somewhere that gives the version of rules_nodejs and give a useful error message if the versions are skewed.

**Comment by alexeagle** [comment] 2018-02-25 16:14
Have a fix for this proposed, https://github.com/alexeagle/bazel_example_new

We still only pick up the top-level `node_modules/@bazel/javascript` though - so if you have `@bazel/typescript` depends on `@bazel/javascript@1.1` but you also installed `@bazel/javascript@1.0` we will end up using 1.0 even if that means rules_typescript doesn't work...

**Comment by alexeagle** [comment] 2018-10-03 13:36
rules_typescript now checks the version of rules_nodejs
https://github.com/bazelbuild/rules_typescript/blob/81114490287357c34f1e632c2e96abea611bf8ff/internal/ts_repositories.bzl#L47
so as long as we keep that up to date, it should solve this issue.

**Closed by alexeagle** 2018-10-03 13:36 UTC
Labels: enhancement
